# Generated by Django 4.2.16 on 2024-09-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NightClub",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("ageReq", models.PositiveIntegerField()),
                ("categories", models.CharField(max_length=255)),
                ("dressCode", models.CharField(max_length=255)),
                ("daysActive", models.CharField(max_length=255)),
                ("hours", models.CharField(max_length=100)),
                ("nightclubID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
