# Generated by Django 5.1.3 on 2024-11-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_remove_order_order_id_remove_order_tickets_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nightclub",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nightclub",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=20, max_digits=20, null=True
            ),
        ),
    ]
