# Generated by Django 5.1.3 on 2024-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_alter_nightclub_latitude_alter_nightclub_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nightclub",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=17, null=True
            ),
        ),
        migrations.AlterField(
            model_name="nightclub",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=15, max_digits=17, null=True
            ),
        ),
    ]
