# Generated by Django 4.2.16 on 2024-09-24 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightclub',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='name',
        ),
        migrations.AddField(
            model_name='nightclub',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nightclub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('normal', 'Normal Cover'), ('vip', 'VIP Cover')], default='Normal', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nightclubs/'),
        ),
        migrations.AlterField(
            model_name='nightclub',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nightclub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.nightclub'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
